[ui]
primary = '#E5F0FF'
secondary = '#E9F1FC'
tertiary = '#D9E3F2'
light = '#C3EFE2'

[ui.theme]
primary = '#4C97FF'
secondary = '#4280D7'
tertiary = '#3373CC'
highlight = '#8ABBFF'

[ui.text]
primary = '#575E75'

[ui.warn]
primary = '#FF8C1A'
light = '#FFB366'

[ui.error]
primary = '#FF661A'
secondary = '#E64D00'

[blocks]
primary = '#0FBD8C'
secondary = '#0DA57A'
tertiary = '#0B8E69'
quaternary = '#0B8E69'

[blocks.motion]
primary = '#4C97FF'
secondary = '#4280D7'
tertiary = '#3373CC'
quaternary = '#3373CC'

[blocks.looks]
primary = '#9966FF'
secondary = '#855CD6'
tertiary = '#774DCB'
quaternary = '#774DCB'

[blocks.sounds]
primary = '#CF63CF'
secondary = '#C94FC9'
tertiary = '#BD42BD'
quaternary = '#BD42BD'

[blocks.events]
primary = '#FFBF00'
secondary = '#E6AC00'
tertiary = '#CC9900'
quaternary = '#CC9900'

[blocks.control]
primary = '#FFAB19'
secondary = '#EC9C13'
tertiary = '#CF8B17'
quaternary = '#CF8B17'

[blocks.sensing]
primary = '#5CB1D6'
secondary = '#47A8D1'
tertiary = '#2E8EB8'
quaternary = '#2E8EB8'

[blocks.operators]
primary = '#59C059'
secondary = '#46B946'
tertiary = '#389438'
quaternary = '#389438'

[blocks.variables]
primary = '#FF8C1A'
secondary = '#FF8000'
tertiary = '#DB6E00'
quaternary = '#DB6E00'

[blocks.lists]
primary = '#FF661A'
secondary = '#FF5500'
tertiary = '#E64D00'
quaternary = '#E64D00'

[blocks.myblocks]
primary = '#FF6680'
secondary = '#FF4D6A'
tertiary = '#FF3355'
quaternary = '#FF3355'

[blocks.debug]
primary = '#29BEB8'
secondary = '#3AA8A4'
